### ISSUE TITLE
Citrix to F5 AS3 conversion fails: TypeError: Cannot read properties of undefined (reading map)

### ISSUE THREAD

**Issue by tjvreugdenhil** [f5devcentral/vscode-f5-flipper#41] opened 2024-07-26 17:41 UTC
When trying to convert Citrix to F5 AS3 format, I get the following error: 
[2024-07-26T17:24:25.552Z] [ERROR]: --- unhandledRejection --- [TypeError: Cannot read properties of undefined (reading '**map**')

Load Citrix ns.conf file
expand "Apps" section
Next to a App on the right side, click { } to convert to JSON
Error is produced and citrix config is not converted. 

OS: Windows 11
Flipper v1.10.1

**Comment by tjvreugdenhil** [comment] 2024-07-26 17:54
This error also happens when **loading the Test NS config.**

**Comment by samualblair** [comment] 2024-07-27 06:29
@tjvreugdenhil, this looks to be a duplicate of the issue I filed [Issue36](https://github.com/f5devcentral/vscode-f5-flipper/issues/36).

While waiting for this to be addressed fully, you may be able to use my workaround, it's just a 2 line modification, [Pull Request Here](https://github.com/f5devcentral/vscode-f5-flipper/pull/38).

**Comment by DumpySquare** [comment] 2024-09-26 01:21
this change will be in the pending v1.11.0 release

**Closed** 2024-09-26 01:21 UTC
Labels: bug
